language: clojure
lein: lein2
before_script:
- lein2 version
script: lein2 do install, test
after_success:
- lein2 pallet-release push
env:
  global:
    secure: Wmw8Qmr/fy2PJrD4sEBz3SPoVt49hNtstmThV20A7I0Y4PFCkHXY4zO3Ueb8ebaRCFPizJXO8PklnRoxNkPmnUCsgObWloc+WooVpqG4gU76ukFbGqbco0dyCaqmwEWxvjRvRKgxRCyzKadZycw8buTj/b0+j85D/nP0q2zPx+g=
